<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AutoClicker</AssemblyName>
    <RootNamespace>AutoClicker</RootNamespace>
    <Platforms>AnyCPU</Platforms>
    <Version>1.0.0</Version>
    <Authors>SaintTemple</Authors>
    <Product>Windows 桌面连点器</Product>
    <Description>基于 C#、WPF 和 MVVM 的 Windows 桌面连点器。</Description>
    <ApplicationIcon>Resources\Icons\autoclicker.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\autoclicker.ico" />
  </ItemGroup>

</Project>
